2024-11-30 10:00:37,712 | WARNING | Неверный тип данных для объекта Runner: int
(<class 'TypeError'>, TypeError('Имя может быть только строкой, передано int'), <traceback object at 0x000002553F625380>)
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 64, in test_run
    runner = Runner(name)
             ^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 19, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-30 10:00:37,718 | INFO | "test_run" выполнен успешно с именем Илья
None
2024-11-30 10:00:37,718 | WARNING | Неверный тип данных для объекта Runner: bool
(<class 'TypeError'>, TypeError('Имя может быть только строкой, передано bool'), <traceback object at 0x000002553F625680>)
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 64, in test_run
    runner = Runner(name)
             ^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 19, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2024-11-30 10:00:37,719 | INFO | "test_run" выполнен успешно с именем Вася
None
2024-11-30 10:00:37,719 | WARNING | Неверный тип данных для объекта Runner: dict
(<class 'TypeError'>, TypeError('Имя может быть только строкой, передано dict'), <traceback object at 0x000002553F625380>)
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 64, in test_run
    runner = Runner(name)
             ^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 19, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано dict
2024-11-30 10:00:37,720 | WARNING | Неверная скорость для Runner: -5
(<class 'ValueError'>, ValueError('Скорость не может быть отрицательной и нулевой, сейчас -5'), <traceback object at 0x000002553F625300>)
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 50, in test_walk
    runner = Runner('TestRunner', speed=speed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 24, in __init__
    raise ValueError(f'Скорость не может быть отрицательной и нулевой, сейчас {speed}')
ValueError: Скорость не может быть отрицательной и нулевой, сейчас -5
2024-11-30 10:00:37,720 | WARNING | Неверная скорость для Runner: -10
(<class 'ValueError'>, ValueError('Скорость не может быть отрицательной и нулевой, сейчас -10'), <traceback object at 0x000002553F5B6780>)
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 50, in test_walk
    runner = Runner('TestRunner', speed=speed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 24, in __init__
    raise ValueError(f'Скорость не может быть отрицательной и нулевой, сейчас {speed}')
ValueError: Скорость не может быть отрицательной и нулевой, сейчас -10
2024-11-30 10:00:37,721 | WARNING | Неверная скорость для Runner: 0
(<class 'ValueError'>, ValueError('Скорость не может быть отрицательной и нулевой, сейчас 0'), <traceback object at 0x000002553EDA5380>)
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 50, in test_walk
    runner = Runner('TestRunner', speed=speed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\pythonProject3name\module_12\test_12_41.py", line 24, in __init__
    raise ValueError(f'Скорость не может быть отрицательной и нулевой, сейчас {speed}')
ValueError: Скорость не может быть отрицательной и нулевой, сейчас 0
2024-11-30 10:00:37,722 | INFO | "test_walk" выполнен успешно со скоростью 5
None
